import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { basename, join, resolve } from "node:path";
import pc from "picocolors";
import { setupGlobalComposerHome, askConfirmation } from "../utils/shell.js";

export interface InitCommandOptions {
  yes?: boolean;
  force?: boolean;
  config?: boolean;
  setComposerHome?: boolean;
}

export async function runInit(
  targetDirectory: string = ".",
  options: InitCommandOptions = {}
): Promise<void> {
  const rootDir = resolve(process.cwd(), targetDirectory);
  const dirName = basename(rootDir);

  console.log(pc.bold(`\n✨ Initializing leoms workspace in: ${pc.cyan(rootDir)}\n`));

  if (!existsSync(rootDir)) {
    mkdirSync(rootDir, { recursive: true });
  }

  const createdItems: string[] = [];
  const skippedItems: string[] = [];

  // 1. Standard open-source directory structure
  const standardDirs = ["packages", "apps", "libs", ".leoms/composer"];

  for (const dir of standardDirs) {
    const abs = join(rootDir, dir);
    if (!existsSync(abs)) {
      mkdirSync(abs, { recursive: true });
      createdItems.push(`${dir}/`);
    } else {
      skippedItems.push(`${dir}/ (already exists)`);
    }
  }

  // 2. Generate pnpm-workspace.yaml
  const pnpmWorkspacePath = join(rootDir, "pnpm-workspace.yaml");
  if (!existsSync(pnpmWorkspacePath) || options.force) {
    const pnpmContent = `# pnpm-workspace.yaml - Generated by leoms
packages:
  - "packages/*"
  - "apps/*"
  - "libs/*"
  - "!**/vendor/**"

# Enable local workspace linking while keeping each repository's lockfile
linkWorkspacePackages: true
sharedWorkspaceLockfile: false
`;
    writeFileSync(pnpmWorkspacePath, pnpmContent, "utf8");
    createdItems.push("pnpm-workspace.yaml");
  } else {
    skippedItems.push("pnpm-workspace.yaml (already exists)");
  }

  // 3. Generate .leoms/composer/config.json
  const composerConfigPath = join(rootDir, ".leoms/composer/config.json");
  if (!existsSync(composerConfigPath) || options.force) {
    const composerConfig = {
      repositories: {
        "local-packages": {
          type: "path",
          url: `${rootDir}/packages/*`,
          options: {
            symlink: true,
          },
        },
        "local-libs": {
          type: "path",
          url: `${rootDir}/libs/*`,
          options: {
            symlink: true,
          },
        },
      },
    };
    writeFileSync(composerConfigPath, JSON.stringify(composerConfig, null, 4) + "\n", "utf8");
    createdItems.push(".leoms/composer/config.json");
  } else {
    skippedItems.push(".leoms/composer/config.json (already exists)");
  }

  // 4. Generate root package.json if missing
  const pkgJsonPath = join(rootDir, "package.json");
  if (!existsSync(pkgJsonPath) || options.force) {
    const pkgContent = {
      name: `${dirName}-workspace`,
      private: true,
    };
    writeFileSync(pkgJsonPath, JSON.stringify(pkgContent, null, 2) + "\n", "utf8");
    createdItems.push("package.json");
  } else {
    skippedItems.push("package.json (already exists)");
  }

  // 5. Generate root .gitignore if missing
  const gitignorePath = join(rootDir, ".gitignore");
  if (!existsSync(gitignorePath) || options.force) {
    const gitignoreContent = `# Dependencies
node_modules/
vendor/

# Build Outputs
dist/
build/

# Leoms Workspace State
.leoms/logs/
.leoms/cache/
.leoms/state/
.leoms/reports/
!.leoms/composer/
`;
    writeFileSync(gitignorePath, gitignoreContent, "utf8");
    createdItems.push(".gitignore");
  } else {
    skippedItems.push(".gitignore (already exists)");
  }

  // 6. Optional leoms.yml (Zero-config by default: only create if requested with --config)
  if (options.config) {
    const leomsYmlPath = join(rootDir, "leoms.yml");
    if (!existsSync(leomsYmlPath) || options.force) {
      const leomsYmlContent = `# leoms.yml - 仅定义项目个性化扩展项，其余包目录与工作区配置均从 pnpm-workspace.yaml 与 .leoms/composer 推导

# 部署配置（默认环境为 production，可通过 --env 覆盖；未配置 script 时自动探测 tools/deploy.sh 或 <project>/scripts/deploy.sh）
deploy:
  env: production
  # script: tools/deploy.sh

# 发版配置（默认推送 origin；开源多仓库可在此添加特定远端）
release:
  remotes:
    - origin
    # - gitee
  # script: tools/release.sh
`;
      writeFileSync(leomsYmlPath, leomsYmlContent, "utf8");
      createdItems.push("leoms.yml (optional config)");
    }
  }

  // 7. Global COMPOSER_HOME setup
  const composerHomeTarget = join(rootDir, ".leoms/composer");
  let shouldSetupComposerHome = options.setComposerHome;

  if (shouldSetupComposerHome === undefined && !options.yes) {
    console.log(pc.bold("\n🔧 Global Composer Configuration:"));
    console.log(
      pc.dim("  Setting COMPOSER_HOME globally in your shell (~/.bashrc or ~/.zshrc)") +
        pc.dim("\n  ensures standard `composer install` works out-of-the-box across terminal sessions.")
    );

    shouldSetupComposerHome = await askConfirmation(
      "Would you like to set COMPOSER_HOME globally for this workspace?",
      false
    );
  }

  let composerHomeResultMsg = "";
  if (shouldSetupComposerHome) {
    const setupRes = await setupGlobalComposerHome(composerHomeTarget, {
      force: options.force,
      yes: options.yes,
    });
    if (setupRes.success) {
      composerHomeResultMsg = pc.green(`✔ ${setupRes.message}`);
    } else {
      composerHomeResultMsg = pc.yellow(`⚠ ${setupRes.message}`);
    }
  }

  // 8. Output Summary
  console.log(pc.bold("\n──────── Initialization Summary ────────"));
  if (createdItems.length > 0) {
    console.log(pc.green("✔ Created files & directories:"));
    for (const item of createdItems) {
      console.log(`  + ${item}`);
    }
  }

  if (skippedItems.length > 0) {
    console.log(pc.dim("\nℹ Skipped existing items:"));
    for (const item of skippedItems) {
      console.log(`  - ${item}`);
    }
  }

  if (composerHomeResultMsg) {
    console.log(`\n${composerHomeResultMsg}`);
  }

  console.log(pc.bold("\n🚀 Next Steps:"));
  console.log(`  1. Run ${pc.cyan("leoms doctor")} to verify your workspace health.`);
  console.log(
    `  2. Install workspace or project dependencies with: ${pc.cyan("leoms install")} (or alias ${pc.cyan("leoms i")})`
  );
  if (!shouldSetupComposerHome) {
    console.log(
      `  3. To run native ${pc.bold("composer")} directly in your shell terminal, persist globally with: ${pc.cyan("leoms init --set-composer-home")}`
    );
  }
  console.log("");
}
